/**
 * data_sharing 付与 CLI
 *
 * 既存プロジェクト (例: vantan_user) の定義に data_sharing エントリを
 * 追加/更新して updateProjectSchema() 経由で保存する。既存の
 * user_data.columns / endpoint / 他の data_sharing エントリは維持したまま、
 * 指定した grant-to プロジェクトへの許可だけを追加・上書きする
 * (同じ project_key の既存エントリがあれば置き換える)。
 *
 * これも register-project.ts と同様、DB に直接アクセスするオペレータ用
 * one-off CLI。通常のプロジェクト管理者 WS セッション
 * (managed_project.update_schema, requireSystemAdmin) に対応する操作を
 * 対話セッション無しで一回限り実行するためのもの。
 *
 * 使い方 (server/ で実行、環境変数 DATABASE_URL が対象 DB を指している必要あり):
 *   tsx scripts/grant-project-data-sharing.ts \
 *     --project vantan_user \
 *     --grant-to aedilis \
 *     --modules profile \
 *     --access read \
 *     --description "施設予約サービスへの学生プロフィール参照許可"
 *
 * --modules は繰り返し指定可能 (例: --modules profile --modules contact)。
 * 省略時は「そのプロジェクトの全モジュール」を共有する定義になる — 通常は
 * 明示的に絞り込むことを推奨する。--access は read (既定) | readwrite。
 * readwrite を指定しても Cernere 側に実際の書き込み共有 API はまだ無いため、
 * 現時点では read と同じ効果 (将来の書き込み共有実装に備えた宣言のみ)。
 *
 * このスクリプトは秘密情報を発行しない (client_id/client_secret は
 * register-project.ts で別途発行済みのものをそのまま使う)。
 */

import { eq } from "drizzle-orm";
import { db } from "../src/db/connection.js";
import * as dbSchema from "../src/db/schema.js";
import { updateProjectSchema } from "../src/project/service.js";
import type { DataShareDefinition, ProjectDefinition } from "../src/project/schema.js";

interface Args {
  project: string;
  grantTo: string;
  modules: string[];
  access: "read" | "readwrite";
  description?: string;
}

function parseArgs(argv: string[]): Args {
  let project = "";
  let grantTo = "";
  const modules: string[] = [];
  let access: "read" | "readwrite" = "read";
  let description: string | undefined;

  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--project") project = argv[++i] ?? "";
    else if (a === "--grant-to") grantTo = argv[++i] ?? "";
    else if (a === "--modules") modules.push(argv[++i] ?? "");
    else if (a === "--access") {
      const v = argv[++i];
      if (v === "read" || v === "readwrite") access = v;
    } else if (a === "--description") description = argv[++i];
  }

  return { project, grantTo, modules: modules.filter(Boolean), access, description };
}

async function main(): Promise<void> {
  const { project, grantTo, modules, access, description } = parseArgs(process.argv.slice(2));
  if (!project || !grantTo) {
    console.error(
      "usage: tsx scripts/grant-project-data-sharing.ts --project <key> --grant-to <projectKey> "
      + "[--modules <mod> ...] [--access read|readwrite] [--description <text>]",
    );
    process.exit(1);
  }

  const rows = await db.select().from(dbSchema.managedProjects)
    .where(eq(dbSchema.managedProjects.key, project)).limit(1);
  if (rows.length === 0) {
    console.error(`project "${project}" not found`);
    process.exit(1);
  }

  const current = rows[0].schemaDefinition as ProjectDefinition;
  const existingShares = (current.data_sharing ?? []).filter((s) => s.project_key !== grantTo);
  const newEntry: DataShareDefinition = {
    project_key: grantTo,
    access,
    ...(modules.length > 0 ? { modules } : {}),
    ...(description ? { description } : {}),
  };

  const nextDefinition = {
    ...current,
    data_sharing: [...existingShares, newEntry],
  };

  const result = await updateProjectSchema(project, nextDefinition);

  console.log("\ndata_sharing updated:\n");
  console.log(`  project        : ${project}`);
  console.log(`  granted to     : ${grantTo}`);
  console.log(`  access         : ${access}`);
  console.log(`  modules        : ${modules.length > 0 ? modules.join(", ") : "(all)"}`);
  console.log(`  status         : ${result.message}`);
  console.log("\nNo secrets are generated by this step (client_id/client_secret already issued separately).\n");
  process.exit(0);
}

main().catch((err) => {
  console.error("grant failed:", err instanceof Error ? err.message : err);
  process.exit(1);
});
